name: sentence_class
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas>=2.0.2
  - pytorch>=1.13.1
  - torchvision
  - torchaudio
  - transformers>=4.30.0
  - datasets>=2.14.0
  - scikit-learn>=1.2.2
  - scipy>=1.10.1
  - matplotlib>=3.7.1
  - pip
  - pip:
    - evaluate>=0.4.0