name: bio-ml
channels:
  - defaults
  - conda-forge
  - bioconda
  - pytorch    # for the official PyTorch builds

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook

  # Deep learning frameworks
  - pytorch         # CPU build; on Apple Silicon this includes MPS backend
  - torchvision
  - torchaudio

  # TensorFlow CPU fallback
  - tensorflow-base  # you still need the base package for macOS

  # Bioinformatics libraries
  - biopython
  - scikit-bio
  - pysam
  - h5py
  - anndata
  - scanpy
  - umap-learn

  # Speedups & utilities
  - numba
  - dask
  - joblib

  # Modeling extras
  - xgboost
  - lightgbm
  - optuna
  - statsmodels

  # (Optional) cheminformatics
  - rdkit

  # In‐environment pip installs (for Apple‐Metal TF plugin)
  - pip
  - pip:
    - tensorflow-macos     # macOS-optimized TF
    - tensorflow-metal     # Apple Metal GPU acceleration
