name: ner
channels:
  - defaults
  - conda-forge

dependencies:
  # core language/runtime
  - python=3.10
  
  # data science & ML
  - numpy>=1.23
  - pandas>=1.5
  - scikit-learn>=1.1
  - scipy>=1.9
  - matplotlib>=3.6
  
  # pytorch (CPU/MPS); if you have CUDA, swap to the appropriate cudatoolkit
  - pytorch>=1.13
  # (Optional GPU builds—for CUDA users, uncomment & adjust)
  # - cudatoolkit=11.7

  # ensure pip is available
  - pip

  # install Hugging Face & evaluation libraries via pip
  - pip:
    - transformers>=4.25
    - datasets>=2.10
    - evaluate>=0.4
